version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: issue_service
      POSTGRES_USER: issue_service
      POSTGRES_PASSWORD: issue_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
